### PR TITLE
Fixes the merge planner.

### LINKED ISSUE #2348: Improve MergePlanner
Series of Long merges can stall the merge pipeline for a long time.

A lot of small splits are then needlessly there, impacting search.

Index partitioning amplify the problem considerably, aswe can very normally end up  piping up 100GB worth of merges.
(3 merge, commit every minute, 20MB/s ingestion).

# Solution

Run small merge with  a higher priority. This means two things.
We need to sort merge opportunity depending on their num_merge_ops, AND
avoid queueing all of them.

The latter part my seem very simple, but one issue is that we still want
the merge planner to queue merge opportunities, regardless of whether or not new splits are received.

### PR DESCRIPTION
**Pull request by fulmicoton**
Fixes the merge planner.
    
This PR tweaks the way the merge planner schedules its merge operation
in a subtle way to avoid adding a lot of large merge operations at the
same time... Hence stalling smaller, with a larger bang-for-the-buck
merge operations.
    
This is done by stopping queue merge operations as soon as push back is
experienced.
    

Closes #2348

### CODE REVIEW

File: quickwit/quickwit-indexing/src/actors/merge_planner.rs [hunk 1]
```diff
@@ -144,47 +132,122 @@ impl MergePlanner {
...
+        //
+        // The reason is that in presence of partitioning, it is very possible
+        // to receive a set of splits opening the opportunity to run a lot "large" merge
+        // operations at the same time.
+        //
+        // These large merge operation will in turn prevent small merge operations
+        // from being executed, when in fact small merge operations should be executed
+        // in priority.
+        //
+        // As an alternative approach, this function push merge operations until it starts
```
Comment (guilload) [inline quickwit/quickwit-indexing/src/actors/merge_planner.rs:208]:
```suggestion
        // As an alternative approach, this function pushes merge operations until it starts
```

File: quickwit/quickwit-indexing/src/actors/merge_planner.rs [hunk 2]
```diff
@@ -144,47 +132,122 @@ impl MergePlanner {
...
+        // experience some push back, and then just "loops".
```
Comment (guilload) [inline quickwit/quickwit-indexing/src/actors/merge_planner.rs:209]:
```suggestion
        // experiencing some push back, and then just "loops".
```

**Review by guilload — APPROVED** [review]
Very nice!
