### PR TITLE
QW-2281: Fix timestamp filters for PSQL

### LINKED ISSUE #2281: Failed to run garbage collection on index caused by a query error "operator does not exist"
Very recently, the garbage collector is not working on my index, the logs are like this:

```
2022-11-10T08:32:12.119Z ERROR quickwit_janitor::actors::garbage_collector: Failed to run garbage collection on index. index_id=quickwit-fts-staging error=Database error: `error returned from database: operator does not exist: timestamp without time zone <= integer`.
2022-11-10T08:33:12.122Z ERROR quickwit_janitor::actors::garbage_collector: Failed to run garbage collection on index. index_id=quickwit-fts-staging error=Database error: `error returned from database: operator does not exist: timestamp without time zone <= integer`.
2022-11-10T08:33:12.171Z ERROR quickwit_janitor::actors::garbage_collector: Failed to run garbage collection on index. index_id=ec2-quickwit-fts-staging error=Database error: `error returned from database: operator does not exist: timestamp without time zone <= integer`.
```

It may be related to my database schema.

### PR DESCRIPTION
**Pull request by ChillFish8**
Fixes #2281 

This fixes the bug introduced by #2152 and adds unit tests to prevent this error from re-occurring.

### CODE REVIEW

File: quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs [hunk 1]
```diff
@@ -259,23 +259,24 @@ fn write_sql_filter<V: Display>(
     sql: &mut String,
     field_name: impl Display,
     filter_range: &FilterRange<V>,
+    value_formatter: impl Fn(&V) -> String,
```
Comment (fmassot) [inline quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs:262]: Nitpick: Using an enum is a bit better to avoid a typo next time we handle a filter that needs a conversion.

(if you are not aware of nitpick meaning, see: https://github.com/quickwit-oss/quickwit/blob/main/CODE_STYLE.md)

File: quickwit/quickwit-metastore/src/tests.rs [hunk 2]
```diff
@@ -2064,6 +2070,61 @@ pub mod test_suite {
                     "list-splits-six",
                 ])
             );
+
+            let query =
+                ListSplitsQuery::for_index(index_id).with_update_timestamp_gte(current_timestamp);
```
Comment (fmassot) [inline quickwit/quickwit-metastore/src/tests.rs:2075]: Here we could run the test with `with_update_timestamp_gte(split_6_create_timestamp)` (just create the variable above when create the split 6), so we can check the filtering too.

**Review by fmassot — APPROVED** [review]
LGTM. Could be nice to improve the test on `update_timestamp_gte`.
