### PR TITLE
Auto-generate Kafka group ID

### LINKED ISSUE #1069: Better error message if missing group.id in kafka source [Papercut]
If the `group.id`  parameter is missing, quickwit will fail adding the source with a non-helpful error.

The doc does not make it clear that this is a required parameter.

Also, I wonder it is not clear what this parameter is and why it is required. Could we set it to quickwit by default?
librdkafka suggest just passing a uuid for user like us.

### PR DESCRIPTION
**Pull request by guilload**
### Description
Auto-generate a group ID derived from the source ID for debugging purposes.

Fixes #1069.

### How was this PR tested?
`make test-all`

### CODE REVIEW

File: quickwit-indexing/src/source/kafka_source.rs [hunk 1]
```diff
@@ -292,18 +301,24 @@ fn previous_position_for_offset(offset: i64) -> Position {
...
 /// Creates a new `KafkaSourceConsumer`.
 fn create_consumer(
+    source_id: &str,
     client_log_level: Option<String>,
     client_params: serde_json::Value,
 ) -> anyhow::Result<Arc<KafkaSourceConsumer>> {
-    let log_level = parse_client_log_level(client_log_level)?;
     let mut client_config = parse_client_params(client_params)?;
+    // We assign partitions manually: we always want one consumer per consumer group.
+    let group_id = new_coolid(&format!("quickwit-{}", source_id));
```
Comment (fulmicoton) [inline quickwit-indexing/src/source/kafka_source.rs:318]: There is a restriction on group_id. Can you project the source id to that restriction?

`can be up to 255 characters in length, and can include the following characters: a-z, A-Z, 0-9, . (dot), _ (underscore), and - (dash).`

**Review by fulmicoton — APPROVED** [review]

**Review by fulmicoton — CHANGES_REQUESTED** [review]
See comment inline

File: quickwit-indexing/src/source/kafka_source.rs (hunk 1 above)
Comment (guilload) [reply quickwit-indexing/src/source/kafka_source.rs:318]: Good catch. I'm going to assume that #1007 will be implemented shortly and merely truncate the generated group ID to here 255 characters.

**Review by fulmicoton — APPROVED** [review]

**Review by fulmicoton — APPROVED** [review]
