### PR TITLE
Handling date without time. Time is then 00:00:00

### LINKED ISSUE #3128: Allow date without time
Right now we cannot have just a date without time.
Parsing via strptime with a date format without time does not work.

The following does not work.
```
        let date_time = parse_date_time_str(
            "2012-05-21",
            &[ DateTimeInputFormat::Strptime(StrptimeParser::from_str("%Y-%m-%d").unwrap(),)],
        )
        .unwrap();
```

### PR DESCRIPTION
**Pull request by fulmicoton**
Closes #3128

### CODE REVIEW

File: quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_format.rs [hunk 1]
```diff
@@ -55,11 +56,32 @@ impl FromStr for StrptimeParser {
...
 impl StrptimeParser {
+    /// Parse a given date according to the datetime format specified during the StrptimeParser
+    /// creation. If the date format does not specific a time, the time will be set to 00:00:00.
+    fn parse_primitive_date_time(
+        &self,
+        date_time_str: &str,
+    ) -> Result<PrimitiveDateTime, time::error::Parse> {
+        let mut parsed = Parsed::new();
+        parsed.parse_items(date_time_str.as_bytes(), self.borrow_items())?;
+        // The parsed datetime seems to time.
```
Comment (ChillFish8) [inline quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_format.rs:67]: I'm not sure what this comment means

File: quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_format.rs [hunk 2]
```diff
@@ -55,11 +56,32 @@ impl FromStr for StrptimeParser {
 }
 
 impl StrptimeParser {
+    /// Parse a given date according to the datetime format specified during the StrptimeParser
+    /// creation. If the date format does not specific a time, the time will be set to 00:00:00.
```
Comment (ChillFish8) [inline quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_format.rs:60]:
```suggestion
    /// creation. If the date format does not provide a specific time, the time will be set to 00:00:00.
```

**Review by ChillFish8 — APPROVED** [review]
Looks good to me overall, some clippy lints outstanding and a couple of tweak to be made to the comments but nothing major.
