### PR TITLE
Require subcommands

### LINKED ISSUE #1372: Failed to parse command arguments: Failed to parse command arguments.
When we give no arguments to quickwit, we get 
the following error.

`Failed to parse command arguments: Failed to parse command arguments.`

The help screen would be nicer.

### PR DESCRIPTION
**Pull request by guilload**
### Description
Require subcommands and display help when no subcommand is provided, fixes #1372.

### How was this PR tested?
```sh
> QW_CONFIG=foo cargo run
error: 'quickwit' requires a subcommand but one was not provided

USAGE:
    quickwit [OPTIONS] <SUBCOMMAND>

For more information try --help

```

### CODE REVIEW

File: quickwit-cli/src/cli.rs [hunk 1]
```diff
@@ -35,15 +35,15 @@ pub fn build_cli<'a>() -> Command<'a> {
                 .help("Config file location")
                 .env("QW_CONFIG")
                 .default_value(DEFAULT_QW_CONFIG_PATH)
-                .global(true)
-                .required(false),
```
Comment (guilload) [inline quickwit-cli/src/cli.rs:39]: `required(false)` is not required when the option has a default value.

File: quickwit-cli/src/cli.rs [hunk 2]
```diff
@@ -35,15 +35,15 @@ pub fn build_cli<'a>() -> Command<'a> {
...
+                .global(true),
         )
         .subcommand(build_run_command().display_order(1))
         .subcommand(build_index_command().display_order(2))
         .subcommand(build_source_command().display_order(3))
         .subcommand(build_split_command().display_order(4))
-        .disable_help_subcommand(true)
```
Comment (guilload) [inline quickwit-cli/src/cli.rs:45]: Sorry for the noise, I was just playing with some options and it got moved.

**Review by fulmicoton — APPROVED** [review]
