### PR TITLE
Timestamp field can now be defined at any field mapping level

### LINKED ISSUE #3531: Timestamp field is only valid if defined at the root document level
Regression coming from this commit: https://github.com/quickwit-oss/quickwit/commit/eeee44b3f075d29868932bfcad24b3aa32d8bef2#diff-2b06f568140d8993ed3037c07df5573caa9f697ce13d55222243f9903327ccd8

### PR DESCRIPTION
**Pull request by fmassot**
Fix #3531 

When we define the `timestamp_field` in the index config, we implicitly define it as a field path. Dots '.' is used as a field name separator. If a dot is part of a field name, it must be escaped.
This is the same logic for tag fields.

Example:
- `timestamp_field: object.timestamp` for a document like `{"object": {"timestmap": 10}}`
- `timestamp_field: my\\.timestamp` for a document like `{"my.timestamp": 10}`

Tests added.

### CODE REVIEW

File: quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs [hunk 1]
```diff
@@ -117,30 +117,25 @@ impl DefaultDocMapper {
...
-            };
-    if let FieldMappingType::DateTime(date_time_option, cardinality) =
-        &timestamp_field_entry.mapping_type
-    {
+    if let FieldMappingType::DateTime(date_time_option, cardinality) = &timestamp_field_type {
         if cardinality != &Cardinality::SingleValue {
             bail!(
-                "Multiple values are forbidden for  the timestamp field \
-                 (`{timestamp_field_name}`)."
+                "Multiple values are forbidden for the timestamp field (`{timestamp_field_path}`)."
```
Comment (guilload) [inline quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs:130]:
```suggestion
                "Timestamp field `{timestamp_field_path}` should be single-valued."
```

File: quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs [hunk 2]
```diff
@@ -584,15 +581,54 @@ mod tests {
     }
 
     #[test]
-    fn test_fail_to_build_doc_mapper_with_non_datetime_timestamp_field() {
+    fn test_timestamp_field_in_object_is_valid() {
```
Comment (guilload) [inline quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs:584]: Let's test field names/paths without quotes. That's also valid, YAML.

File: quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs [hunk 3]
```diff
@@ -541,6 +566,33 @@ fn field_name_for_field_path(field_path: &[&str]) -> String {
...
+    let mut current_path_fragment = String::new();
+    let mut escaped = false;
+    for char in field_path_as_str.chars() {
+        if escaped {
+            current_path_fragment.push(char);
+            escaped = false;
+        } else if char == '\\' {
+            escaped = true;
+        } else if char == '.' {
+            field_path.push(current_path_fragment.clone());
```
Comment (guilload) [inline quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs:584]: `mem::replace`

File: quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs [hunk 4]
```diff
@@ -1096,4 +1148,23 @@ mod tests {
             serde_json::json!("010203")
         );
     }
+
+    #[test]
+    fn test_field_path_for_field_name() {
```
Comment (guilload) [inline quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs:1153]: What about string starting or ending with a `.` vs `\.`?

**Review by guilload — APPROVED** [review]

File: quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs (hunk 4 above)
Comment (fmassot) [reply quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs:1153]: Yes... I thought about this. We don't do any validation for tags and timestamp fields, I was going to open an issue on this.
