### PR TITLE
Fix and clean cluster members.

### LINKED ISSUE #1982: Watching clusters members does not return an updated `me` member

### PR DESCRIPTION
**Pull request by fmassot**
Fix #1982.

And I also changed a bit the way we use the member watcher.

Note:  the current watcher is broken if we want to use up-to-date properties of cluster members. Example: we start a node with the server `searcher` and restart afterward with another server. Chitchat will probably not detect a change in readiness and the member watcher of other nodes will not receive member changes. And the other nodes will have their search pool with this no-more searcher node.

PTAL.

### CODE REVIEW

File: quickwit/quickwit-cluster/src/cluster.rs [hunk 1]
```diff
@@ -246,22 +232,45 @@ impl Cluster {
...
     }
 
-    /// Return `members` list
-    pub fn members(&self) -> Vec<ClusterMember> {
-        self.members.borrow().clone()
+    /// Returns ready [`ClusterMember`]s built directly from the current state of the cluster.
+    pub async fn ready_members_from_cluster_state(&self) -> Vec<ClusterMember> {
+        let cluster_state = self.state().await;
+        let mut ready_nodes = cluster_state.ready_nodes.clone();
+        let is_self_node_ready = cluster_state
```
Comment (fmassot) [inline quickwit/quickwit-cluster/src/cluster.rs:256]: ok I admit, this is ugly. Adding a method on `ClusterState` would make it nicer but for now `ClusterState` is just used for the API so I did not want to "enrich" it right now.

File: quickwit/quickwit-search/src/search_client_pool.rs [hunk 2]
```diff
@@ -167,41 +176,15 @@ impl SearchClientPool {
     /// When a client pool is created, the thread that monitors cluster members
     /// will be started at the same time.
     pub async fn create_and_keep_updated(
-        current_members: &[ClusterMember],
```
Comment (fmassot) [inline quickwit/quickwit-search/src/search_client_pool.rs:170]: Passing `current_members` and a member `WatchStream` is, IMHO, a wrong usage of a watch stream.
The watch stream always start with the last seen values. And we always send at least the "self" member, so we always have something. At least self.

File: quickwit/quickwit-cluster/src/cluster.rs [hunk 3]
```diff
@@ -209,32 +210,17 @@ impl Cluster {
...
-                        }
-                        member_res.ok()
-                    })
-                    .collect_vec();
-                members.push(me.clone());
-
+            while let Some(mut members_set) = node_change_receiver.next().await {
+                let cluster_state_snapshot = chitchat.lock().await.state_snapshot();
+                // `members_set` does not contain `self`.
+                members_set.insert(self_node_id.clone());
```
Comment (fmassot) [inline quickwit/quickwit-cluster/src/cluster.rs:216]: This fixed the issue.

Comment (fmassot) [reply quickwit/quickwit-cluster/src/cluster.rs:216]: But I broke the `is_self`.

File: quickwit/quickwit-cluster/src/cluster.rs [hunk 4]
```diff
@@ -62,8 +62,6 @@ pub struct ClusterMember {
     pub generation: u64,
     /// Gossip advertise address.
     pub gossip_advertise_addr: SocketAddr,
-    /// If true, it means self.
```
Comment (fmassot) [inline quickwit/quickwit-cluster/src/cluster.rs:65]: Not used currently.

File: quickwit/quickwit-cluster/src/cluster.rs [hunk 5]
```diff
@@ -510,35 +539,39 @@ mod tests {
...
             .iter()
             .map(|member| member.gossip_advertise_addr)
             .collect();
         let expected_members = vec![cluster.gossip_listen_addr];
         assert_eq!(members, expected_members);
         assert!(!cluster.is_self_node_ready().await);
-        let cluster_state = cluster.state().await;
-        let self_node_state_not_ready = cluster_state
-            .state
+        assert_eq!(cluster.ready_members_from_chitchat_state().await.len(), 0);
```
Comment (fulmicoton) [inline quickwit/quickwit-cluster/src/cluster.rs:550]: I suspect clippy will annoy you 
and tell you to make it

assert!(cluster.ready_members_from_chitchat_state().await.is_empty());

**Review by fulmicoton — APPROVED** [review]
Great job! The code is much cleaner
