### PR TITLE
Fix spinner on index selection #2420.

### LINKED ISSUE #2420: Spinner on index selection combo box keeps spinning if the requests returns no index.
The list itself keeps showing "Loading"

### PR DESCRIPTION
**Pull request by fmassot**
Fix #2420

### CODE REVIEW

File: quickwit/quickwit-ui/src/components/IndexSideBar.tsx [hunk 1]
```diff
@@ -37,22 +37,28 @@ function IndexAutocomplete(props: IndexMetadataProps) {
   const [open, setOpen] = React.useState(false);
   const [options, setOptions] = React.useState<readonly IndexMetadata[]>([]);
   const [value, setValue] = React.useState<IndexMetadata | null>(null);
-  const loading = open && options.length <= 1;
+  const [loading, setLoading] = React.useState(false);
+  // We want to show the circular progress only if we are loading some results and
+  // when there is no option avaiable.
+  const showLoading = loading && options.length == 0;
```
Comment (ChillFish8) [inline quickwit/quickwit-ui/src/components/IndexSideBar.tsx:43]: Nitpick: Use `===` rather than `==` for the length comparision.

Comment (fmassot) [reply quickwit/quickwit-ui/src/components/IndexSideBar.tsx:43]: oh thanks, you're right... I always forget that :/
