### PR TITLE
Remove publisher finalize and shut down property a merge pipeline wit…

### LINKED ISSUE #2262: Merge pipeline stops if an actor in the indexing pipeline fails.
This is due to the fact that the publisher will send an exit command to the merge planner.

### PR DESCRIPTION
**Pull request by fmassot**
Fix #2262 

+ kill a merge pipeline when there is no more indexing pipeline registered on a given (index_id, source_id).

I think we should also kill an indexing pipeline when we shut it down (but will see that in another PR).

2 tests added.

### CODE REVIEW

File: quickwit/quickwit-indexing/src/actors/indexing_service.rs [hunk 1]
```diff
@@ -385,19 +386,40 @@ impl IndexingService {
                     }
                 },
             );
-        // Evict merge pipelines that are not needed or failing.
+        // Evict and and killing merge pipelines that are not needed.
```
Comment (fulmicoton) [inline quickwit/quickwit-indexing/src/actors/indexing_service.rs:389]:
```suggestion
        // Evict and kill merge pipelines that are not needed.
```

**Review by fulmicoton — APPROVED** [review]

**Review by fulmicoton — APPROVED** [review]

**Review by fulmicoton — APPROVED** [review]
