### PR TITLE
Fix metastore URI credentials leak

### LINKED ISSUE #1672: Credentials leak when displaying metastore URI in logs (PostgreSQL)

### PR DESCRIPTION
**Pull request by guilload**
### Description
Fix metastore URI credentials leak. Fix #1672.

### How was this PR tested?
Added unit test

### CODE REVIEW

File: quickwit-metastore/src/metastore/postgresql_metastore.rs [hunk 1]
```diff
@@ -51,18 +52,18 @@ mod pg_error_code {
 }
 
 /// Establishes a connection to the given database URI.
-async fn establish_connection(database_uri: &str) -> MetastoreResult<Pool<Postgres>> {
+async fn establish_connection(connection_uri: &Uri) -> MetastoreResult<Pool<Postgres>> {
```
Comment (guilload) [inline quickwit-metastore/src/metastore/postgresql_metastore.rs:55]: Generalizing the use of `Uri` in the metastore implementation so that we don't inadvertently display the credentials when manipulating the URI as a raw string.

File: quickwit-metastore/src/metastore/postgresql_metastore.rs [hunk 2]
```diff
@@ -51,18 +52,18 @@ mod pg_error_code {
...
     let pool_options = PgPoolOptions::new()
         .max_connections(CONNECTION_POOL_MAX_SIZE)
         .idle_timeout(Duration::from_secs(1))
         .acquire_timeout(Duration::from_secs(2));
-    let mut pg_connect_options: sqlx::postgres::PgConnectOptions = database_uri.parse()?;
-    pg_connect_options.log_statements(LevelFilter::Debug);
+    let mut pg_connect_options: PgConnectOptions = connection_uri.as_str().parse()?;
+    pg_connect_options.log_statements(LevelFilter::Info);
```
Comment (guilload) [inline quickwit-metastore/src/metastore/postgresql_metastore.rs:61]: Changed to `Info`. Do we really wanted `Debug`?

**Review by fulmicoton — APPROVED** [review]
