### PR TITLE
Fix CLI inconsistencies #1320

### LINKED ISSUE #1320: [Papercut] Fix some CLI inconsistencies
- [ ] Remove `data-dir` option when not necessary
- [ ] Fix the display order of some commands (1. `config`, 2. `index`, 3. `source`/`split`, 4. other options)
- [ ] Make required options such as `config` or `index` actually required
- [ ] Set default values with `default_value`
- [ ] Add aliases (`ls`, `rm`, ...) whenever possible

### PR DESCRIPTION
**Pull request by kalil-pelissier**
### Description

Fix CLI inconsistencies:

- [ ] Remove data-dir option when not necessary
- [x] Fix the display order of some commands (1. config, 2. index, 3. source/split, 4. other options)
- [x] Make required options such as config or index actually required
- [ ] Set default values with default_value
- [x] Add aliases (ls, rm, ...) whenever possible

### How was this PR tested?

Try local CLI + run tests

### Content

- Fix the display order of some commands (1. config, 2. index, 3. source/split, 4. other options) 
- Add aliases (`ls` for list, `del` for delete, `desc` for describe)
- Remove data-dir when not necessary

close #1320

### CODE REVIEW

File: quickwit/quickwit-cli/src/cli.rs [hunk 1]
```diff
@@ -37,10 +37,10 @@ pub fn build_cli<'a>() -> Command<'a> {
...
                 .global(true),
         )
-        .subcommand(build_run_command().display_order(1))
-        .subcommand(build_index_command().display_order(2))
-        .subcommand(build_source_command().display_order(3))
-        .subcommand(build_split_command().display_order(4))
+        .subcommand(build_index_command().display_order(1))
+        .subcommand(build_source_command().display_order(2))
+        .subcommand(build_split_command().display_order(2))
+        .subcommand(build_run_command().display_order(3))
```
Comment (fulmicoton) [inline quickwit/quickwit-cli/src/cli.rs:43]: `run`, `index`, `source`, `split` makes more sense.

**Comment by fulmicoton** [comment]
@kalil-pelissier thank you Kalil.

I made the PR "draft" since it seems like it is a work in progress.
If you want to have it merged independently, that's even better. Just switch it to "Ready for Review", and edit the PR description with the actual content of the PR.

We require contributors to sign a CLA electronically. The process is rather fast.
You work is still under the AGPL license, but it gives Quickwit the right to also emit commercial licenses.

File: quickwit/quickwit-cli/src/cli.rs (hunk 1 above)
Comment (kalil-pelissier) [reply quickwit/quickwit-cli/src/cli.rs:43]: Ok, it was already this display order before my update. Maybe I didn't understand the task:

- `Fix the display order of some commands (1. config, 2. index, 3. source/split, 4. other options)` 

Is there any modifications to make for this task ?

Comment (fulmicoton) [reply quickwit/quickwit-cli/src/cli.rs:43]: Ah well.... I guess I disagree with @guilload.

I'm ok with that order then.

Comment (fulmicoton) [reply quickwit/quickwit-cli/src/cli.rs:43]: (apologies for the noise)

Comment (guilload) [reply quickwit/quickwit-cli/src/cli.rs:43]: You changed `1, 2, 3, 4` to `1, 2, 2, 3`.

Comment (guilload) [reply quickwit/quickwit-cli/src/cli.rs:43]: Regarding the order of the commands, I did not express myself correctly. I mean the order of the options in the commands: `1. config, 2. index, 3. checkpoint/source/split, 4. other options/flags`.

**Comment by guilload** [comment]
`data_dir` is only necessary for commands such as `index ingest, index merge, index  search` that write intermediates data structure (index files, caches) `.

Let's no worry about setting default values for now.

**Comment by kalil-pelissier** [comment]
@guilload I think I'm missing something. I search where `data_dir` is not used but each time this option is given to the `load_quickwit_config` function to generate a config:

```rust
    let quickwit_config = load_quickwit_config(&args.config_uri, args.data_dir).await?;
```

I don't think that I should remove the option in the subcommand and let a default value be set?

**Comment by guilload** [comment]
`load_quickwit_config(&args.config_uri, None)` is fine. We already do that for a bunch of commands.

**Comment by kalil-pelissier** [comment]
Ok so for example the `index create` command don't need `data-dir` option?

File: quickwit/quickwit-cli/src/index.rs [hunk 2]
```diff
@@ -89,7 +89,9 @@ pub fn build_index_command<'a>() -> Command<'a> {
             Command::new("ingest")
                 .about("Indexes JSON documents read from a file or streamed from stdin.")
                 .args(&[
-                    arg!(--index <INDEX> "ID of the target index"),
+                    arg!(--index <INDEX> "ID of the target index")
+                        .display_order(1)
+                        .required(true),
```
Comment (evanxg852000) [inline quickwit/quickwit-cli/src/index.rs:94]: By default, arg is required so the pattern is more like use `required(false)` to make it optional. The exception I know is when you use `.conflicts_with()`

Comment (kalil-pelissier) [reply quickwit/quickwit-cli/src/index.rs:92]: Ok, I had doubts that args is required by default. 

So that means there is nothing to do for this task: `Make required options such as config or index actually required`.

I will remove the commit to get it back as it was.

File: quickwit/quickwit-cli/src/cli.rs [hunk 3]
```diff
@@ -35,7 +35,8 @@ pub fn build_cli<'a>() -> Command<'a> {
                 .help("Config file location")
                 .env("QW_CONFIG")
                 .default_value(DEFAULT_QW_CONFIG_PATH)
-                .global(true),
+                .global(true)
+                .display_order(0),
```
Comment (guilload) [inline quickwit/quickwit-cli/src/cli.rs:39]: +1

**Review by guilload — APPROVED** [review]

File: quickwit/quickwit-cli/src/cli.rs (hunk 3 above)
Comment (kalil-pelissier) [reply quickwit/quickwit-cli/src/cli.rs]: @guilload I just fixed the `display_order` but there is another trouble with the tests.
The option `data_dir` that I have deleted is required for tests so I removed my last commit.

**Comment by guilload** [comment]
Merged, congrats on your first contribution @kalil-pelissier 🎉
