### PR TITLE
Fixes Bug in FileStorage

### LINKED ISSUE #2304: Bug in file based metastore
When stressing hte file metastore, the following sometimes shows up.

```
2022-11-14T07:09:08.318Z  INFO quickwit_metastore::checkpoint: delta=∆(/home/fulmicoton/git/sandboxes/partition-id/dataset.json:(00000000002692200860..00000000002779334428]) checkpoint=Ckpt(/home/fulmicoton/git/sandboxes/partition-id/dataset.json:00000000002692200860)
2022-11-14T07:09:11.721Z  INFO quickwit_metastore::checkpoint: delta=∆(/home/fulmicoton/git/sandboxes/partition-id/dataset.json:(00000000002779334428..00000000002865385542]) checkpoint=Ckpt(/home/fulmicoton/git/sandboxes/partition-id/dataset.json:00000000002779334428)
2022-11-14T07:09:14.459Z  INFO quickwit_metastore::checkpoint: delta=∆(/home/fulmicoton/git/sandboxes/partition-id/dataset.json:(00000000002865385542..00000000002952206871]) checkpoint=Ckpt(/home/fulmicoton/git/sandboxes/partition-id/dataset.json:00000000002865385542)
2022-11-14T07:09:14.682Z ERROR quickwit_metastore::metastore::file_backed_metastore::lazy_file_backed_index: fetch-metadata-error error=InvalidManifest { message: "EOF while parsing a string at line 4323 column 44" }
2022-11-14T07:09:17.639Z  INFO quickwit_metastore::checkpoint: delta=∆(/home/fulmicoton/git/sandboxes/partition-id/dataset.json:(00000000002952206871..00000000003037394790]) checkpoint=Ckpt(/home/fulmicoton/git/sandboxes/partition-id/dataset.json:00000000002952206871)
2022-11-14T07:09:20.562Z  INFO quickwit_metastore::checkpoint: delta=∆(/home/fulmicoton/git/sandboxes/partition-id/dataset.json:(00000000003037394790..00000000003125958654]) checkpoint=Ckpt(/home/fulmicoton/git/sandboxes/partition-id/dataset.json:00000000003037394790)
2022-11-14T07:09:23.660Z  INFO quickwit_metastore::checkpoint
```

### PR DESCRIPTION
**Pull request by fulmicoton**
Writing in the file storage was not atomic.

So if some other process was polling the file storage for instance, it could end up reading some version of the meta file that was partially written, and therefore invalid JSON.

This is the bug that was observed in #2304.

This PR also prevents the file metastore from reloading the data due to the polling loop, if it is the process acactually writing the metastore.

Closes #2304

### CODE REVIEW

File: quickwit/quickwit-storage/src/local_file_storage.rs [hunk 1]
```diff
@@ -183,11 +183,15 @@ impl Storage for LocalFileStorage {
...
-
         let mut reader = payload.byte_stream().await?.into_async_read();
-        let mut f = tokio::fs::File::create(full_path).await?;
-        tokio::io::copy(&mut reader, &mut f).await?;
-
+        let named_temp_file = tempfile::NamedTempFile::new_in(&self.root)?;
+        let (temp_std_file, temp_filepath) = named_temp_file.into_parts();
+        let mut temp_tokio_file = tokio::fs::File::from_std(temp_std_file);
+        tokio::io::copy(&mut reader, &mut temp_tokio_file).await?;
+        temp_tokio_file.flush().await?;
```
Comment (ChillFish8) [inline quickwit/quickwit-storage/src/local_file_storage.rs:191]: Is the intention here to make sure the file gets dropped immediately or is this to ensure data is correctly persisted to disk?

 If it's the latter we should use `sync_data` or `sync_all`.

Comment (fulmicoton) [reply quickwit/quickwit-storage/src/local_file_storage.rs:191]: the main intention is to make sure readers don't read a partially written file. Adding an fsync is not a bad idea.

Comment (fulmicoton) [reply quickwit/quickwit-storage/src/local_file_storage.rs:195]: added a `sync_data` on the file and the parent directory.

@chillfish8 can you resume the review?

File: quickwit/quickwit-storage/src/local_file_storage.rs [hunk 2]
```diff
@@ -180,14 +180,24 @@ impl Storage for LocalFileStorage {
...
+        let named_temp_file = tempfile::NamedTempFile::new_in(parent_dir)?;
+        let (temp_std_file, temp_filepath) = named_temp_file.into_parts();
+        let mut temp_tokio_file = tokio::fs::File::from_std(temp_std_file);
+        tokio::io::copy(&mut reader, &mut temp_tokio_file).await?;
+        temp_tokio_file.flush().await?;
+        temp_tokio_file.sync_data().await?;
+        temp_filepath
+            .persist(&full_path)
+            .map_err(|err| StorageErrorKind::Io.with_error(err))?;
+        tokio::fs::File::open(parent_dir).await?.sync_data().await?;
```
Comment (ChillFish8) [inline quickwit/quickwit-storage/src/local_file_storage.rs:200]: Nitpick: For readability purposes, I think we should use `OpenOptions` rather than `File::open()` to avoid confusion, even though I understand why we're opening this directory, it feels odd opening this a `File`.

**Review by ChillFish8 — APPROVED** [review]
