### PR TITLE
Normalize Error Messages

### LINKED ISSUE #3759: Normalize error messages
> The error message given by the Display representation of an error type should be lowercase without trailing punctuation and typically concise.

> [Examples of error messages](https://rust-lang.github.io/api-guidelines/interoperability.html#examples-of-error-messages)
"unexpected end of file"
"provided string was not `true` or `false`"
"invalid IP address syntax"
"second time provided was later than self"
"invalid UTF-8 sequence of {} bytes from index {}"
"environment variable was not valid unicode: {:?}"

As per [Rust API Guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html), this will reduce noise during code reviews.

### PR DESCRIPTION
**Pull request by csditchfield**
### Description

Changes all error messages to lowercase and removes trailing punctuation.
Updates CODE_STYLE.md

Closes #3759

### How was this PR tested?

`cargo nextest run --features=postgres`
`make fix`

### CODE REVIEW

File: quickwit/quickwit-actors/src/channel_with_priority.rs [hunk 1]
```diff
@@ -89,9 +89,9 @@ impl<M> From<flume::TrySendError<M>> for TrySendError<M> {
 
 #[derive(Clone, Copy, Debug, Error, Eq, PartialEq)]
 pub enum RecvError {
-    #[error("No message are currently available.")]
+    #[error("no message are currently available")]
     NoMessageAvailable,
-    #[error("All sender were dropped and no pending messages are in the channel.")]
+    #[error("all sender were dropped and no pending messages are in the channel")]
```
Comment (guilload) [inline quickwit/quickwit-actors/src/channel_with_priority.rs:94]:
```suggestion
    #[error("all senders were dropped and no pending messages are in the channel")]
```

File: quickwit/quickwit-config/src/source_config/mod.rs [hunk 2]
```diff
@@ -340,7 +340,7 @@ impl TryFrom<KinesisSourceParamsInner> for KinesisSourceParams {
     fn try_from(value: KinesisSourceParamsInner) -> Result<Self, Self::Error> {
         if value.region.is_some() && value.endpoint.is_some() {
             return Err(
-                "Kinesis source parameters `region` and `endpoint` are mutually exclusive.",
+                "kinesis source parameters `region` and `endpoint` are mutually exclusive",
```
Comment (guilload) [inline quickwit/quickwit-config/src/source_config/mod.rs:343]: nit: We can keep uppercase for proper nouns such as `Quickwit`, `Kafka`, `Kinesis`, `Pulsar`, ...

**Review by guilload — APPROVED** [review]
Approved! Thanks a lot for the contribution.

A few tests must be fixed in the Rust crates, and the REST API tests. `make fmt` must also be applied. You can check out our [`Contributing`](https://github.com/quickwit-oss/quickwit/blob/main/CONTRIBUTING.md) guide for more details.

**Comment by guilload** [comment]
I will merge this before conflicts get out of hand and fix the tests in a separate PR. Thank you @csditchfield!
