### PR TITLE
handle track_total_size on request body

### LINKED ISSUE #4705: track_total_hits of elasticsearch_api's SearchBody is ignored
**Describe the bug**
track_total_hits in the Elastic Search API can be specified in two places:
- SearchBody ([ES doc](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-your-data.html#track-total-hits))
- SearchQueryParams ([ES doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html))

However, in Quickwit, SearchBody.track_total_hits is ignored. Only SearchQueryParams.track_total_hits is taken into account.

**Expected behavior**
Both SearchBody.track_total_hits and SearchQueryParams.track_total_hits should be taken into account there:
https://github.com/quickwit-oss/quickwit/blob/f37d8b68af6b1b0ff0c3fbd25e0297d35914adb8/quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs#L269

According to this [ES doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-query-params), if both are specified, the one in SearchQueryParams wins.

### PR DESCRIPTION
**Pull request by PSeitz**
closes #4705

### Description

Describe the proposed changes made in this PR.

### How was this PR tested?

Describe how you tested this PR.

### CODE REVIEW

File: quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs [hunk 1]
```diff
@@ -269,10 +269,14 @@ fn build_request_for_es_api(
 
     let max_hits = search_params.size.or(search_body.size).unwrap_or(10);
     let start_offset = search_params.from.or(search_body.from).unwrap_or(0);
-    let count_hits = match search_params.track_total_hits {
+    let count_hits = match search_params
+        .track_total_hits
+        .as_ref()
```
Comment (fulmicoton) [inline quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs:274]: nitpick.

I think we can make `TrackTotalHits` Copy and remove the as_ref.

**Review by fulmicoton — APPROVED** [review]
