### PR TITLE
Reduce attack surface on the FileStorage.

### LINKED ISSUE #53: Investigate security considerations on the local file storage
The URI resolution scheme for the file system can have some important risk implication.
We also want to handle file:///var/local and the incorrect but common file://var/local format. 

We need to make sure someone cannot access files that are not under the root directory using the "../" schemefor instnace.

Generally speaking: we should put some thoughts in it. 

----

UPDATE:

We want to enforce the fact that path accessed by the FileStorage are child path of the FileStorage root.

### PR DESCRIPTION
**Pull request by fulmicoton**
We prevent people from using relative path including a `..` in the FileStorage.

Closes #53

### CODE REVIEW

File: quickwit/quickwit-storage/src/local_file_storage.rs [hunk 1]
```diff
@@ -71,23 +76,55 @@ impl LocalFileStorage {
...
+        ignore_error_kind!(ErrorKind::NotFound, fs::remove_file(full_path).await)?;
+        Ok(())
+    }
+}
+
+/// Ensure that the path given does not include any ".." for security reasons.
+///
+/// In order to reduce the attack surface, we want to make sure the `FileStorage`
+/// only access/delete files that are children of its root_directory.
+fn ensure_no_parent_dir_double_dot(path: &Path) -> StorageResult<()> {
```
Comment (ChillFish8) [inline quickwit/quickwit-storage/src/local_file_storage.rs:103]: I think this could be called something like `ensure_valid_path` or similar as this does technically do more than just ensure the parent isn't a `..` for example, `/todo` will also get rejected by this routine.

Comment (fulmicoton) [reply quickwit/quickwit-storage/src/local_file_storage.rs]: If you just have "nitpicks" comment, please mark the CR as approved. This is a practise that is a bit specific to quickwit: we are all in different timezone, so it is critical that we keep the process asynchronous when possible.

Comment (fulmicoton) [reply quickwit/quickwit-storage/src/local_file_storage.rs]: (I did the rename and will abuse my privilege and merge that  PR  :) )

Comment (ChillFish8) [reply quickwit/quickwit-storage/src/local_file_storage.rs]: Ah apologies 😅

Comment (fulmicoton) [reply quickwit/quickwit-storage/src/local_file_storage.rs]: No problem! you could not know! :)
