### PR TITLE
Fix fieldnorms option is not propagated to tantivy

### LINKED ISSUE #1844: Text fieldnorms option is not propagated to tantivy
The option is basically ignored and fieldnorms are always generated. With a log management and analytics use case in mind, the default should be false.

### PR DESCRIPTION
**Pull request by boraarslan**
Fixes #1844

### CODE REVIEW

File: quickwit-search/src/lib.rs [hunk 1]
```diff
@@ -205,6 +205,10 @@ pub async fn single_node_search(
     .map_err(|err| {
         SearchError::InternalError(format!("Failed to build doc mapper. Cause: {}", err))
     })?;
+
+    // Try to build query against current schema
+    let _query = doc_mapper.query(doc_mapper.schema(), search_request)?;
+
```
Comment (boraarslan) [inline quickwit-search/src/lib.rs:211]: `single_node_search` now builds the query, so in cases where this function is used to search, if the query is invalid, it returns an error instead of returning a result with 0 hits. If this is something we don't want, I can revert the changes.

File: quickwit-search/src/tests.rs [hunk 2]
```diff
@@ -310,34 +310,51 @@ async fn test_single_node_filtering() -> anyhow::Result<()> {
...
+                    {}
+                  - name: ts
+                    type: i64
+                    fast: true
+                  - name: temperature
+                    type: i64
+                    fast: true
+            "#,
+        fieldnorms_str
+    );
```
Comment (boraarslan) [inline quickwit-search/src/tests.rs:349]: This is atrocious, I know. I will fix this before merging.

File: quickwit-search/src/lib.rs [hunk 3]
```diff
@@ -205,6 +205,10 @@ pub async fn single_node_search(
     .map_err(|err| {
         SearchError::InternalError(format!("Failed to build doc mapper. Cause: {}", err))
     })?;
+
+    // Try to build query against current schema
```
Comment (guilload) [inline quickwit-search/src/lib.rs:209]:
```suggestion
    // Validates the query by effectively building it against the current schema.
```

File: quickwit-search/src/tests.rs [hunk 4]
```diff
@@ -310,34 +310,51 @@ async fn test_single_node_filtering() -> anyhow::Result<()> {
...
     )
-    .await?;
-    assert_eq!(single_node_response.num_hits, 0);
-    assert_eq!(single_node_response.hits.len(), 0);
-
+    .await;
+    assert!(single_node_response.is_err());
+    assert_eq!(
+        single_node_response.err().map(|err| err.to_string()),
+        Some("Invalid query: Field does not exists: 'tag'".to_string())
```
Comment (guilload) [inline quickwit-search/src/tests.rs:317]: Can you fix the code that raises this error:
```Invalid query: field `tag` does not exist.```

**Review by guilload — APPROVED** [review]
LGTM except for the ugly test :)

File: quickwit-search/src/lib.rs (hunk 1 above)
Comment (boraarslan) [reply quickwit-search/src/lib.rs:211]: Yes, `single_node_search` is only used in CLI. I added the request validation as well.

File: quickwit-search/src/tests.rs (hunk 4 above)
Comment (boraarslan) [reply quickwit-search/src/tests.rs:317]: I believe the error message comes from tantivy's `QueryParserError::FieldDoesNotExist`.
